on: [push]

jobs:
  hello_world_job:
    runs-on: ["self-hosted","ub22"]
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
